import { SchedulingRule } from './types';

export const MOCK_RULES: SchedulingRule[] = [
  {
    id: 'radiology_mri_ct',
    status: 'active',
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-04-10T14:30:00Z',
    calendarId: 'radiology',
    calendarName: 'Radiology Department',
    appointmentTypes: ['MRI Exam', 'CT Scan'],
    description: 'This MRI/CT scan appointment is for patients who have been referred by their doctor. Patients must submit their referral letter in chat to book their appointment. Patients without a referral letter will be handed over to a human agent.',
    eligibility: 'criteria',
    eligibilityCriteria: ['Patient must have a doctor referral', 'Patient must submit referral letter in chat'],
    ineligibleAction: 'handover',
    ineligibleCallNumber: '',
    bookingMethod: 'request',
    directConfig: { slotsToOffer: 3, advanceAmount: 2, advanceUnit: 'weeks', noSlotsAction: 'handover', noSuitableAction: 'offer_next', maxRetries: 3 },
    preferredSlotsCount: 3,
    fields: [
      { propertyId: 'full_name', label: 'Full Name', required: true },
      { propertyId: 'mobile_number', label: 'Phone Number', required: true },
      { propertyId: 'date_of_birth', label: 'Date of Birth', required: true },
      { propertyId: 'email', label: 'Email Address', required: false },
    ],
    reschedulePolicy: 'yes',
    rescheduleAmount: 24,
    rescheduleUnit: 'hours',
    rescheduleCallNumber: '',
    cancelPolicy: 'no_call',
    cancelAmount: 0,
    cancelUnit: 'hours',
    cancelCallNumber: '+65 6123 4567',
    alerts: {
      enabled: true,
      alertUsers: ['admin_4'],
      triggers: ['new_booking', 'cancel_reschedule'],
    },
  },
  {
    id: 'wellness_screening',
    status: 'active',
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-04-08T09:00:00Z',
    calendarId: 'wellness',
    calendarName: 'Wellness Center',
    appointmentTypes: ['Health Screening', 'Executive Checkup'],
    description: 'Wellness screening packages for general health assessment. Patients should fast for 12 hours before blood work.',
    eligibility: 'anyone',
    eligibilityCriteria: [],
    ineligibleAction: 'handover',
    ineligibleCallNumber: '',
    bookingMethod: 'direct',
    directConfig: { slotsToOffer: 3, advanceAmount: 1, advanceUnit: 'months', noSlotsAction: 'inform', noSuitableAction: 'offer_next', maxRetries: 2 },
    preferredSlotsCount: 3,
    fields: [
      { propertyId: 'full_name', label: 'Full Name', required: true },
      { propertyId: 'mobile_number', label: 'Phone Number', required: true },
      { propertyId: 'email', label: 'Email Address', required: true },
      { propertyId: 'date_of_birth', label: 'Date of Birth', required: true },
    ],
    reschedulePolicy: 'yes',
    rescheduleAmount: 2,
    rescheduleUnit: 'days',
    rescheduleCallNumber: '',
    cancelPolicy: 'yes',
    cancelAmount: 2,
    cancelUnit: 'days',
    cancelCallNumber: '',
    alerts: {
      enabled: true,
      alertUsers: ['admin_5'],
      triggers: ['new_booking'],
    },
  },
  {
    id: 'dr_smith_consult',
    status: 'draft',
    createdAt: '2026-02-20T12:00:00Z',
    updatedAt: '2026-04-05T16:00:00Z',
    calendarId: 'dr_smith',
    calendarName: 'Dr. Smith - Cardiology',
    appointmentTypes: ['Consultation'],
    description: 'Cardiology consultation with Dr. Smith. Available Mon-Fri 9am-5pm.',
    eligibility: 'anyone',
    eligibilityCriteria: [],
    ineligibleAction: 'handover',
    ineligibleCallNumber: '',
    bookingMethod: 'link',
    directConfig: { slotsToOffer: 3, advanceAmount: 2, advanceUnit: 'weeks', noSlotsAction: 'handover', noSuitableAction: 'offer_next', maxRetries: 3 },
    preferredSlotsCount: 3,
    fields: [
      { propertyId: 'full_name', label: 'Full Name', required: true },
      { propertyId: 'mobile_number', label: 'Phone Number', required: true },
      { propertyId: 'reason_for_visit', label: 'Reason for Visit', required: false },
    ],
    reschedulePolicy: 'no_handover',
    rescheduleAmount: 0,
    rescheduleUnit: 'hours',
    rescheduleCallNumber: '',
    cancelPolicy: 'no_handover',
    cancelAmount: 0,
    cancelUnit: 'hours',
    cancelCallNumber: '',
    alerts: {
      enabled: false,
      alertUsers: [],
      triggers: [],
    },
  },
];
